!!model.Config
clipboard:
    OOM Killer查询: cat /var/log/messages|grep -i kill
    Redis批量删除: redis-cli -h 127.0.0.1 -p 6379 -a password -n 0 keys "*name*" | xargs
        redis-cli -h 127.0.0.1 -p 6379 -a password -n 0 del
    MySQL连接: mysql -h 地址 -P 端口 -u 用户名 -p 密码
    yum源配置目录: cd /etc/yum.repos.d/
configuration:
    Dictionary: http://dict.youdao.com/w/eng/
    Version: 1.2.3
    ViewConnectionBar: false
    WindowsBaseDrive: 'C:'
    WaitForInitTime: 200
    ShowWelcomePage: false
    ViewUtilitiesBar: false
    WindowPositionSize: 217,16,862,1004
    ViewBottomQuickBar: true
    DefaultPuttyUsername: root
    DatabasePath: C:\Git\notebook\01-工作\01-环境资源\02-测试环境\ssh.csv
feature:
    transfer: true
    vnc: false
menus:
-   cmd: notepad.exe
    name: notebook
    type: menu
-   cmd: C:\Program Files\SingleWare\luyten-0.5.0.exe
    name: Java反编译
    type: menu
-   cmd: null
    name: null
    type: separator
program:
    PuttyExecutable: C:\ProgramData\chocolatey\bin\PUTTY.EXE
    MinttyExecutable: C:\tools\msys64\usr\bin\mintty.exe
    PlinkExecutable: C:\ProgramData\chocolatey\bin\PLINK.EXE
    ScpExecutable: C:\Program Files\WinSCP\WinSCP.exe
    KeyGeneratorExecutable: C:\ProgramData\chocolatey\bin\PUTTYGEN.EXE
