!!model.Config
clipboard:
    OOM Killer查询: cat /var/log/messages|grep -i kill
    Redis批量删除: redis-cli -h 127.0.0.1 -p 6379 -a password -n 0 keys "*name*" | xargs
        redis-cli -h 127.0.0.1 -p 6379 -a password -n 0 del
    MySQL连接: mysql -h 地址 -P 端口 -u 用户名 -p 密码
    yum源配置目录: cd /etc/yum.repos.d/
configuration:
    Dictionary: http://dict.youdao.com/w/eng/
    ViewConnectionBar: false
    WindowsBaseDrive: 'C:'
    WaitForInitTime: 200
    ShowWelcomePage: false
    ViewUtilitiesBar: false
    WindowPositionSize: 374,24,1216,1004
    ViewBottomQuickBar: false
    DefaultPuttyUsername: root
    DatabasePath: D:\GitHub\notebook\01-工作\01-环境资源\ssh.csv
feature:
    transfer: true
menus:
-   cmd: notepad.exe
    name: notebook
    type: menu
-   cmd: D:\SingleWare\luyten-0.5.0.exe
    name: Java反编译
    type: menu
-   cmd: null
    name: null
    type: separator
-   cmd: taskkill /F /IM Putty.exe /IM Mintty.exe
    name: 关闭所有Putty程序
    type: menu
program:
    PuttyExecutable: D:\kitty\kitty.exe
    MinttyExecutable: C:\Program Files\Git\usr\bin\mintty.exe
    PlinkExecutable: D:\kitty\klink.exe
    ScpExecutable: D:\WinSCP\WinSCP.exe
    KeyGeneratorExecutable: D:\kitty\kittygen.exe
